### ISSUE TITLE
テクスチャ、マテリアルは一つのみ対応?

### ISSUE THREAD

**Issue by enjoysoftware** [kusaanko/Blender_XFileSupport_BVE#2]
Blender 2.9(2.8でも)でxファイルを出力すると、Blenderのマテリアル設定画面で一番上にあるマテリアル(この場合ではotherface)が、UVマッピングを無視してすべての面に適用されてしまいますが、対処法などありますでしょうか。   
この場合では、直方体の上の面と下の面にunderを適用していて、側面にotherfaceを適用しています。  
よろしくお願いいたします。
![panel](https://user-images.githubusercontent.com/47489953/140002298-cce2f4fe-d913-4842-a0b8-a1348705bf87.png)

Blender上のモデリング画面: 
![blender](https://user-images.githubusercontent.com/47489953/140002368-ede5c969-3541-402d-87d0-35272a610d58.png)

エクスポート後:
![exported](https://user-images.githubusercontent.com/47489953/140002450-1d108e24-65ba-40e0-b4d1-73139069812d.png)

対象のxファイル: [リンク](https://drive.google.com/file/d/1Lv0NuyzIykpsiANzPsCcTh7wfHHwZ0uX/view?usp=sharing)

**Comment by kusaanko** [comment]
ご意見ありがとうございます。
複数のマテリアルには現在未対応です。
今後のアップデートで対応することにします。

**Comment by enjoysoftware** [comment]
了解しました。ありがとうございます。

**Comment by kusaanko** [comment]
XFileSupport 2.1.0にて対応しました。先程リリースしましたのでお試しください。

**Comment by enjoysoftware** [comment]
正常に動作しました。機能を追加してくださりありがとうございます。
