### ISSUE TITLE
material name error

### ISSUE THREAD

**Issue by yy8413** [kusaanko/Blender_XFileSupport_BVE#3]
Export doesn't work. Irregularity occurs at a constant rate. The material name in blender is written to the X file. You can work around this by editing and deleting the text.
![WS000598](https://user-images.githubusercontent.com/94049618/141101083-78a981b8-629e-4d00-beab-82c9d55a64bc.JPG)
.

**Comment by kusaanko** [comment]
You can set it off by unchecking “Export material name” in export dialog. X file can have material name and it is not illegal. You can load the X file in any DirectX applications.(ex. Bve 5 or 6, strview5) This feature is used when you arrange the material index.
あと、もし喋れるなら日本語でもいいですよ。

**Comment by yy8413** [comment]
解決しました。ありがとうございます。
