### ISSUE TITLE
Cannot export selected only.

### ISSUE THREAD

**Issue by adfriz** [kusaanko/Blender_XFileSupport_BVE#4]
Tested on blender 3.6 and OpenBVE object viewer.

Step:
 1. Make multiple object in blender
 2. Click one of it and export to .x either binary or text format.
 3. Open the .x in openbve object viewer 
 4. All object is exported into one .x file not just the one i selected.

Workaround that i found: hide all object except the one you want export in blender and it will export the only one that visible in viewport.
----------------
blender 3.6とOpenBVEオブジェクトビューアでテスト。

ステップ
 1. blenderで複数のオブジェクトを作成する。
 2. そのうちの1つをクリックし、バイナリまたはテキスト形式で.xにエクスポートします。
 3. .xをopenbveオブジェクトビューアで開きます。
 4. 選択したオブジェクトだけでなく、すべてのオブジェクトが1つの.xファイルにエクスポートされます。

私が見つけた回避策：blenderでエクスポートしたいオブジェクト以外のオブジェクトをすべて非表示にすると、ビューポートに表示されているオブジェクトだけがエクスポートされます。

**Comment by kusaanko** [comment]
It is a specification. Export all objects that are not hidden. I will put the function of exporting only selected objects on the development list. Thanks.

**Comment by kusaanko** [comment]
This function was added to XFileSupport version 2.2.0. Please update!
How to use:
Check the checkbox "Export only selected objects" in save dialog.
