### ISSUE TITLE
Blender4.0使用時のError

### ISSUE THREAD

**Issue by Riku-Horn** [kusaanko/Blender_XFileSupport_BVE#5]
Blender4.0.1でこのプラグインを使おうとしたところ、このようなエラーが表示されエクスポートできませんでした
（Blender3.6では正常にエクスポートできました）。

![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/112320600/7b1aef14-e0e3-4eb5-a959-902e26602745)

**Comment by kusaanko** [comment]
ご指摘ありがとうございます。Blenderが4にアップデートされたことに気づきませんでした。
少し調べたところ、少し複雑な変更が必要なようです。
ただいま多忙でして、早急にアップデートを行うことはできませんが、来週末ごろにはアップデートに取り掛かります。

**Comment by kusaanko** [comment]
ただいまアップデート完了しました。Blenderを起動すると自動でインストールが完了します。もしくは手動でReleasesからダウンロードお願いします。
メッセージの通りBlenderを再起動するとアップデートが適用されるので、それで試してみてください。

**Comment by Riku-Horn** [comment]
エラーが消えたことをこちらでも確認しました。
ご対応ありがとうございました。

![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/112320600/b11c55fd-38e9-4573-be49-21df217660e9)
