### ISSUE TITLE
プリンシブルBSDFのベースカラーが反映されない

### ISSUE THREAD

**Issue by Riku-Horn** [kusaanko/Blender_XFileSupport_BVE#6]
画像のような棒状のモデルについて、プリンシブルBSDFのベースカラーでグレーを指定しましたが BVEでは白のままになっています。
Blender4.0.2, Blender_XFileSupport_BVE 3.1.0 を使用しています。

↓Blenderでの表示
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/112320600/9edcac02-1950-4525-8e8c-6667806b3915)
↓BVEでの表示
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/112320600/a2715a91-fc62-4e9d-918b-4b150a032619)

**Comment by kusaanko** [comment]
問題はBlenderの標準の放射の色が変わったことのようです。
BVEでは放射が使用されるようで、Blender 4.0より前では標準の色が黒でしたが、Blender 4.0からは白になったようです。
プリシンプルBSDFの放射から色を黒に変更してみてください。

**Comment by Riku-Horn** [comment]
放射の色をグレーにしたところBVE上でも期待通りグレーで表示されました。
ありがとうございました

![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/112320600/a65462c0-ad33-4d56-b49a-43427c0035af)

**Comment by kusaanko** [comment]
今までと同じ発色ですと、放射はRGBA(0, 0, 0, 1)になります。
白っぽくしていきますとBVEでも白っぽくなっていきます。
よろしくお願いします。
