### ISSUE TITLE
テクスチャが反映されない

### ISSUE THREAD

**Issue by ShakeRiceGit** [kusaanko/Blender_XFileSupport_BVE#7]
このアドオンを使用して出力したXファイルを**DirectX9で**表示させようとしています。
Blender4.0の際に制作したファイルでは問題なく表示させることができたのですが、
Blender4.1の今回制作したファイルを表示させようとすると、テクスチャが貼られず真っ白な状態になってしまいます。

出力されたXファイル自体を見てみると、大きく異なる点としてはマテリアル欄に「TextureFilename」の記載がない状態でした。
バージョンが変化したことによる不具合が考えられるのでしょうか？
今回はBlender_XFileSupport_BVE 3.2.0、前回はおそらく3.1.0を使用していると思います。

何度も再インストールし直してみたり、前回制作した「player.x」をもう一度出力してみたのですが、
それでもテクスチャ設定ができていないようです...

↓テクスチャが表示できない「box.x」
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/fb2892a3-b3e7-4311-92d2-042864e7445f)
↓「player.x」
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/fa10de5f-2138-42ab-a17b-b7776d80fa87)

↓DirectX9で表示。
左が「player.x」、右が「box.x」
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/bd1f4685-fccc-4cf7-a279-a87dbebf535a)

ファイル：[Source.zip](https://github.com/kusaanko/Blender_XFileSupport_BVE/files/14872241/Source.zip)

**Comment by ShakeRiceGit** [comment]
出力時の「Export only necessary data」をオフにした状態や、
Blender_XFileSupport_BVE 3.1.0で出力したものでも試してみましたが、表示されませんでした。

**Comment by kusaanko** [comment]
ご報告ありがとうございます。
テクスチャに関する部分は長らく変更していないので（Blender2の頃からずっと同じです）、Blender4.0の時にはできていたというところが気になります。
また明日調査します。

**Comment by kusaanko** [comment]
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/39370373/d63d3b06-a0e3-4d58-af17-15b8dcf69ed5)
こんな感じで問題なく表示されています。
実際のノードを見せていただけませんか？

**Comment by kusaanko** [comment]
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/39370373/f4a999ce-44c4-497b-95f1-8cead4ac93f5)
Blender 4.0、4.1ともにこんな感じで問題なく表示できています。
ノードを見せていただけませんか？

**Comment by ShakeRiceGit** [comment]
こんな感じです。
Blender初心者なので、この辺りは特に触ったことがありません。
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/962bdce3-7d7a-4bb6-951b-00f35a92f132)

[こちらのサイト](https://vook.vc/n/5755)を見ながら、画像を張り付けて出力しただけです。

**Comment by kusaanko** [comment]
そのマテリアルにマテリアル名を設定して（半角英数字でお願いします）、出力時に「マテリアル名を出力する」にチェックをしてもう一度出力されたファイルの中身を見てみてください。
正常にできていれば「Material {」の間に設定したマテリアル名が書かれるはずです。

**Comment by kusaanko** [comment]
英語設定ですと「マテリアル名を出力する」は「Export material name」になります

**Comment by ShakeRiceGit** [comment]
ご丁寧にありがとうございます。
デフォルト名から変更して出力した結果きちんとマテリアル名が出力されましたが、
おそらくテクスチャファイルのパスが出力されていないせいか、いまだ同じく真っ白に表示されています。
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/cec820ed-80e1-44f1-a1ca-197870e719ce)
↓「player.x」
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/54d024e0-fce2-47e3-b114-3d00785c9d39)

**Comment by ShakeRiceGit** [comment]
ちなみに、box.xの「Material box{}」内に無理やり「TextureFilename」を書き加えて試してみたのですが、
テクスチャ自体は認識されるもののうまく表示されないです。
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/0fa683ab-9d26-4db2-a275-4f2ccfa61ca6)

**Comment by kusaanko** [comment]
Blenderでは正常に表示されているんですよね？
こちらで色々試しましたが原因がいまいちわかりません。
もしよければBlender起動から保存までの動画か詳細な手順を共有していただけると助かります。

**Comment by ShakeRiceGit** [comment]
わかりました。では、新規作成から出力までの手順を記載します。

↓新規作成→マテリアル「box」を作成し、テクスチャ「box.jpg」を設定する。
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/5f388862-117b-45bd-9d71-d3cc74deed59)

↓設定後
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/230a0eae-9275-42ec-8f3f-4b5fe1a75930)

↓「File / Export / DirectX XFile(.x)」より出力する。
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/ff5ffe62-e004-40ff-a011-039b97518b2f)

行っていることはこれだけです。
何か不足している情報などありましたら、教えていただきたいです。

↓DirectX9で表示
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/ce1a5a85-2a35-482e-93a7-7c8a7eeccc58)

**Comment by ShakeRiceGit** [comment]
報告です！
バージョン関係の不具合の可能性を考えて、
「**Blender3.6**」かつ「Blender_XFileSupport_BVE **"2.2.0"**」を使用して出力してみたところ、うまく表示させることができました！
![image](https://github.com/kusaanko/Blender_XFileSupport_BVE/assets/102935742/5a9bfe79-3ca2-451e-b2f0-bf20c1c88fc6)

**Comment by kusaanko** [comment]
クリーンインストール状態のWindowsでBlender 4.1をインストールしてみましたが正常に動きました。
以下手順です
1. Generalで初期状態のプロジェクトを作成
1. マテリアル設定からBase Colorのアイコンを選びImage Textureを選択
1. Openで **保存先と同じディレクトリ** にある.png画像を選択
1. レイアウト、オブジェクトモードの状態でDirectX XFileを選択して画像と **同じディレクトリ内** に初期設定の状態で保存

**Comment by ShakeRiceGit** [comment]
再度「Blender4.1」「Blender_XFileSupport_BVE 3.2.0」にて、プロジェクト・画像・出力先を同じディレクトリにして出力してみましたが、変わらずテクスチャが貼られず真っ白な状態でした。

そして、問題は解決していないのですが、[こちら](https://github.com/kusaanko/Blender_XFileSupport_BVE/issues/7#issuecomment-2041064789)の方法によって正しく出力できることが分かったため、とりあえずはこの方法で現在の制作を進めさせていただこうかなと思います。

長々とお付き合いくださりありがとうございました！

**Comment by kusaanko** [comment]
また何かわかったことなどありましたら情報提供お待ちしております。
こちらでも何か分かればまたこちらのissueに投稿させていただきます。
